/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.awt.*;
import java.awt.geom.Line2D;
import java.util.ArrayList;

/**
 *
 * @author a-berger.1
 */
public class main extends javax.swing.JFrame {

    int startingX;
    int startingY;
    Point pointStart;
    Point pointEnd;
    ArrayList<Line2D> lines = new ArrayList<Line2D>();
    boolean mouseReleased = false;
    boolean undoWire = false;

    /**
     * Creates new form main
     */
    public main() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        WireColor = new javax.swing.ButtonGroup();
        Workspace = new javax.swing.JPanel();
        groundPanel = new javax.swing.JPanel();
        groundLabel = new javax.swing.JLabel();
        sourcePanel = new javax.swing.JPanel();
        sourceLabel = new javax.swing.JLabel();
        toolbar = new javax.swing.JPanel();
        toolbarLabel = new javax.swing.JLabel();
        toolPanel = new javax.swing.JPanel();
        WirePanel = new javax.swing.JPanel();
        WireColorPanel = new javax.swing.JPanel();
        Black = new javax.swing.JRadioButton();
        Red = new javax.swing.JRadioButton();
        Grey = new javax.swing.JRadioButton();
        Pink = new javax.swing.JRadioButton();
        removeWiresPanel = new javax.swing.JPanel();
        undoLastWireBtn = new javax.swing.JButton();
        clearWiresBtn = new javax.swing.JButton();
        gatesPanel = new javax.swing.JPanel();
        Sidebar = new javax.swing.JPanel();
        textPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        navBox = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Workspace.setBackground(new java.awt.Color(255, 255, 255));
        Workspace.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        Workspace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                WorkspaceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                WorkspaceMouseReleased(evt);
            }
        });
        Workspace.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                WorkspaceMouseDragged(evt);
            }
        });

        groundPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 2, new java.awt.Color(0, 0, 0)));

        groundLabel.setBackground(new java.awt.Color(255, 255, 255));
        groundLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        groundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        groundLabel.setText("Ground");
        groundLabel.setToolTipText("");

        javax.swing.GroupLayout groundPanelLayout = new javax.swing.GroupLayout(groundPanel);
        groundPanel.setLayout(groundPanelLayout);
        groundPanelLayout.setHorizontalGroup(
            groundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
        );
        groundPanelLayout.setVerticalGroup(
            groundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sourcePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        sourceLabel.setBackground(new java.awt.Color(255, 255, 255));
        sourceLabel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        sourceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sourceLabel.setText("Source");
        sourceLabel.setToolTipText("");

        javax.swing.GroupLayout sourcePanelLayout = new javax.swing.GroupLayout(sourcePanel);
        sourcePanel.setLayout(sourcePanelLayout);
        sourcePanelLayout.setHorizontalGroup(
            sourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sourceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sourcePanelLayout.setVerticalGroup(
            sourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sourceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        toolbar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        toolbarLabel.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        toolbarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toolbarLabel.setText("Toolbar");
        toolbarLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        toolPanel.setLayout(new java.awt.GridLayout(0, 1));

        WirePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Wires", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        WirePanel.setLayout(new java.awt.GridLayout(0, 1));

        WireColorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Color", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 14))); // NOI18N
        WireColorPanel.setLayout(new java.awt.GridLayout(0, 1, 5, 0));

        WireColor.add(Black);
        Black.setText("Black");
        WireColorPanel.add(Black);

        WireColor.add(Red);
        Red.setText("Red");
        WireColorPanel.add(Red);

        WireColor.add(Grey);
        Grey.setText("Grey");
        WireColorPanel.add(Grey);

        WireColor.add(Pink);
        Pink.setText("Pink");
        WireColorPanel.add(Pink);

        WirePanel.add(WireColorPanel);

        removeWiresPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Remove", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 14))); // NOI18N
        removeWiresPanel.setLayout(new java.awt.GridLayout(0, 1));

        undoLastWireBtn.setText("Undo Last Wire");
        undoLastWireBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoLastWireBtnActionPerformed(evt);
            }
        });
        removeWiresPanel.add(undoLastWireBtn);

        clearWiresBtn.setText("Clear Wires");
        clearWiresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearWiresBtnActionPerformed(evt);
            }
        });
        removeWiresPanel.add(clearWiresBtn);

        WirePanel.add(removeWiresPanel);

        toolPanel.add(WirePanel);

        gatesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gates", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 24))); // NOI18N

        javax.swing.GroupLayout gatesPanelLayout = new javax.swing.GroupLayout(gatesPanel);
        gatesPanel.setLayout(gatesPanelLayout);
        gatesPanelLayout.setHorizontalGroup(
            gatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );
        gatesPanelLayout.setVerticalGroup(
            gatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        toolPanel.add(gatesPanel);

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
            .addComponent(toolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarLayout.createSequentialGroup()
                .addComponent(toolbarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout WorkspaceLayout = new javax.swing.GroupLayout(Workspace);
        Workspace.setLayout(WorkspaceLayout);
        WorkspaceLayout.setHorizontalGroup(
            WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkspaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sourcePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(groundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkspaceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        WorkspaceLayout.setVerticalGroup(
            WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkspaceLayout.createSequentialGroup()
                .addComponent(sourcePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(groundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(Workspace, gridBagConstraints);

        Sidebar.setBackground(new java.awt.Color(0, 0, 0));
        Sidebar.setLayout(new java.awt.GridBagLayout());

        textPanel.setBackground(new java.awt.Color(204, 204, 204));
        textPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        textPanel.setFocusable(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setDoubleBuffered(true);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis efficitur augue nec libero pharetra faucibus quis vel enim. Phasellus semper ultrices tempus. Sed malesuada venenatis consequat. Donec nec tortor bibendum, consectetur nunc nec, convallis massa. Nunc semper tristique vehicula. Nam ac mauris accumsan, tincidunt mi eu, mollis purus. In commodo non odio tincidunt rhoncus. Fusce dignissim risus nec nisl finibus, id vehicula mi tincidunt. Nunc vitae sapien id enim finibus congue.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin ullamcorper est eu massa posuere auctor. Quisque aliquam vehicula hendrerit. In mauris risus, pellentesque nec laoreet a, vulputate in sapien. Nunc at auctor eros. Quisque pellentesque suscipit ante non tincidunt. Vestibulum eget euismod magna, nec scelerisque quam. Pellentesque et semper sem, non lobortis diam.\n\nCurabitur nec massa a augue varius egestas a eget elit. Suspendisse potenti. Ut pulvinar cursus metus, et convallis nibh consequat consequat. Ut sagittis diam ut nulla ornare, convallis vestibulum tortor pellentesque. Cras laoreet augue ut mi scelerisque, sit amet blandit diam ullamcorper. Sed a velit in odio dapibus ultricies id quis sem. Donec quis congue quam, ac efficitur purus. Maecenas id est sed mauris luctus congue. Cras malesuada nec dolor sed ullamcorper.\n\nMaecenas malesuada pharetra aliquet. Ut non sollicitudin libero. Suspendisse quis suscipit diam. Nulla dapibus enim laoreet tellus convallis, a faucibus risus condimentum. Nulla suscipit magna suscipit consequat luctus. Nunc dapibus ipsum tristique imperdiet commodo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum finibus tincidunt arcu. Sed eros nisl, dictum vel auctor eu, rhoncus at lacus. Mauris dictum libero eget laoreet iaculis.\n\nPraesent nec volutpat velit. Duis libero mi, placerat nec risus eu, ultrices ultrices tellus. Fusce est lacus, molestie eu lobortis id, egestas quis nulla. Nam molestie elit id lectus pharetra consequat. Mauris erat quam, interdum sed fringilla eu, tincidunt in ex. Morbi vel semper turpis, eget accumsan lacus. Nam eu efficitur erat.\n\nGenerated 5 paragraphs, 318 words, 2184 bytes of Lorem Ipsum");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 10));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setDoubleBuffered(true);
        jTextArea1.setDragEnabled(true);
        jTextArea1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jTextArea1.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        Sidebar.add(textPanel, gridBagConstraints);

        navBox.setBackground(new java.awt.Color(204, 204, 204));
        navBox.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout navBoxLayout = new javax.swing.GroupLayout(navBox);
        navBox.setLayout(navBoxLayout);
        navBoxLayout.setHorizontalGroup(
            navBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        navBoxLayout.setVerticalGroup(
            navBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        Sidebar.add(navBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(Sidebar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WorkspaceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WorkspaceMousePressed
        // TODO add your handling code here:
        pointStart = evt.getPoint();

    }//GEN-LAST:event_WorkspaceMousePressed

    private void WorkspaceMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WorkspaceMouseDragged
        // TODO add your handling code here:
        pointEnd = evt.getPoint();
        repaint();
    }//GEN-LAST:event_WorkspaceMouseDragged

    private void WorkspaceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WorkspaceMouseReleased
        // TODO add your handling code here:
        mouseReleased = true;
        lines.add(new Line2D.Double(pointStart, pointEnd));
        repaint();
        pointStart = null;
    }//GEN-LAST:event_WorkspaceMouseReleased

    private void clearWiresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearWiresBtnActionPerformed
        // TODO add your handling code here:
        int i;
        
        while (!lines.isEmpty()) {
            i = lines.size()-1;
            lines.remove(i);
        }
        repaint();

    }//GEN-LAST:event_clearWiresBtnActionPerformed

    private void undoLastWireBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoLastWireBtnActionPerformed
        // TODO add your handling code here:
        if(!lines.isEmpty()) {
        lines.remove(lines.size() - 1);
        undoWire = true;
        repaint();
        }

    }//GEN-LAST:event_undoLastWireBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2 = (Graphics2D) g;
        if (pointStart != null) {
            g.setColor(Color.RED);
            g2.setStroke(new BasicStroke(10));
            g2.drawLine(pointStart.x, pointStart.y, pointEnd.x, pointEnd.y);

        }
        if (mouseReleased || undoWire) {
            for (int i = 0; i < lines.size(); i++) {
                g.setColor(Color.RED);
                g2.setStroke(new BasicStroke(10));
                g2.draw(lines.get(i));
            }
            mouseReleased = false;
            undoWire = false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Black;
    private javax.swing.JRadioButton Grey;
    private javax.swing.JRadioButton Pink;
    private javax.swing.JRadioButton Red;
    private javax.swing.JPanel Sidebar;
    private javax.swing.ButtonGroup WireColor;
    private javax.swing.JPanel WireColorPanel;
    private javax.swing.JPanel WirePanel;
    private javax.swing.JPanel Workspace;
    private javax.swing.JButton clearWiresBtn;
    private javax.swing.JPanel gatesPanel;
    private javax.swing.JLabel groundLabel;
    private javax.swing.JPanel groundPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel navBox;
    private javax.swing.JPanel removeWiresPanel;
    private javax.swing.JLabel sourceLabel;
    private javax.swing.JPanel sourcePanel;
    private javax.swing.JPanel textPanel;
    private javax.swing.JPanel toolPanel;
    private javax.swing.JPanel toolbar;
    private javax.swing.JLabel toolbarLabel;
    private javax.swing.JButton undoLastWireBtn;
    // End of variables declaration//GEN-END:variables
}
